AWSTemplateFormatVersion: "2010-09-09"
Description:
  Create VPC and Subnet

Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "Creating VPC and Subnet"
        Parameters:
          - Project
      - Label:
          default: "VPC Network Configuration"
        Parameters:
          - VPCCIDR
          - AZ1Parameter
          - AZ2Parameter
          - PublicSubnet1CIDR
          - PublicSubnet2CIDR
          - PrivateSubnet1CIDR
          - PrivateSubnet2CIDR

Parameters:
  Project:
    Type: String
    Default: "EC2Sample"
    Description: Project Name

  VPCCIDR:
    Type: String
    Default: "10.0.0.0/16"
    Description: VPC Network

  AZ1Parameter:
    Type: String
    Default: 'us-west-1b'
    Description: Availability Zone 1

  AZ2Parameter:
    Type: String
    Default: 'us-west-1c'
    Description: Availability Zone 2

  PublicSubnet1CIDR:
    Type: String
    Default: "10.0.0.0/24"
    Description: Public Subnet in AZ1

  PublicSubnet2CIDR:
    Type: String
    Default: "10.0.1.0/24"
    Description: Public Subnet in AZ2

  PrivateSubnet1CIDR:
    Type: String
    Default: "10.0.10.0/24"
    Description: Private Subnet in AZ1

  PrivateSubnet2CIDR:
    Type: String
    Default: "10.0.11.0/24"
    Description: Private Subnet in AZ1

Resources:
  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: !Ref VPCCIDR
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      InstanceTenancy: default
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Name
          Value: !Sub "${Project}-VPC"
# Internet Gateway
  InternetGateway:
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Name
          Value: !Sub "${Project}-IGW"

  InternetGatewayAttachment:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

# Subnet
  PublicSubnet1:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Ref AZ1Parameter
      CidrBlock: !Ref PublicSubnet1CIDR
      VpcId: !Ref VPC
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Name
          Value: PublicSubnet1

  PublicSubnet2:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Ref AZ2Parameter
      CidrBlock: !Ref PublicSubnet2CIDR
      VpcId: !Ref VPC
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Name
          Value: PublicSubnet2

  PrivateSubnet1:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Ref AZ1Parameter
      CidrBlock: !Ref PrivateSubnet1CIDR
      VpcId: !Ref VPC
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Name
          Value: PrivateSubnet1

  PrivateSubnet2:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Ref AZ2Parameter
      CidrBlock: !Ref PrivateSubnet2CIDR
      VpcId: !Ref VPC
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Name
          Value: PrivateSubnet2

# Route Table
  PublicRouteTable1:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Name
          Value: PublicRoute1

  PublicRouteTable2:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Name
          Value: PublicRoute2

  PrivateRouteTable1:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Name
          Value: PrivateRoute1

  PrivateRouteTable2:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Name
          Value: PrivateRoute2

# Route
  PublicRoute1:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref PublicRouteTable1
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref InternetGateway

  PublicRoute2:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref PublicRouteTable2
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref InternetGateway

# RouteTable Associate
  PublicSubnet1RouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable1

  PublicSubnet2RouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable2

  PrivateSubnet1RouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable1

  PrivateSubnet2RouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRouteTable2

Outputs:
  VPC:
    Description: VPC ID
    Value: !Ref VPC
    Export:
      Name: !Sub "${Project}-Vpc"

  VPCCIDR:
    Description: VPC CIDR
    Value: !Ref VPCCIDR
    Export:
      Name: !Sub "${Project}-VpcCidr"

  PublicSubnet1:
    Description: "Public Subnet, AZ:1, Range: 10.0.0.0/24"
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub "${Project}-PublicSubnet1"

  PublicSubnet2:
    Description: "Public Subnet, AZ:2, Range: 10.0.1.0/24"
    Value: !Ref PublicSubnet2
    Export:
      Name: !Sub "${Project}-PublicSubnet2"

  PrivateSubnet1:
    Description: "Private Subnet, AZ:1, Range: 10.0.10.0/24"
    Value: !Ref PrivateSubnet1
    Export:
      Name: !Sub "${Project}-PrivateSubnet1"

  PrivateSubnet2:
    Description: "Private Subnet, AZ:2, Range: 10.0.11.0/24"
    Value: !Ref PrivateSubnet2
    Export:
      Name: !Sub "${Project}-PrivateSubnet2"


  PublicSubnet1CIDR:
    Description: "Public Subnet CIDR, AZ:1, Range: 10.0.0.0/24"
    Value: !Ref PublicSubnet1CIDR
    Export:
      Name: !Sub "${Project}-PublicSubnet1Cidr"

  PublicSubnet2CIDR:
    Description: "Public Subnet CIDR, AZ:1, Range: 10.0.0.0/24"
    Value: !Ref PublicSubnet2CIDR
    Export:
      Name: !Sub "${Project}-PublicSubnet2Cidr"

  PublicRouteTable1:
    Description: "Public Route, AZ:1, Route: Local/Internet"
    Value: !Ref PublicRouteTable1
    Export:
      Name: !Sub "${Project}-PublicRoute1"

  PublicRouteTable2:
    Description: "Public Route, AZ:2, Route: Local/Internet"
    Value: !Ref PublicRouteTable2
    Export:
      Name: !Sub "${Project}-PublicRoute2"
