AWSTemplateFormatVersion: "2010-09-09"
Description:
  EC2 Instance Create

Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "Create Kubernetes clusters"
        Parameters:
          - Project
      - Label:
          default: "EC2Instance Configuration"
        Parameters:
          - KeyPairName
          - EC2InstanceAMI
          - EC2InstanceInstanceType
          - EC2InstanceVolumeType
          - EC2InstanceVolumeSize
          - EC2InstanceSubnet
          - SSHAccessSourceIP

Parameters:
  Project:
    Type: String
    Default: "k8s"
    Description: Project Name

#EC2Instance
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: ""
    Description: Select Key Pair

  EC2InstanceAMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
    Description: Select AMI

  EC2InstanceInstanceType:
    Type: String
    Default: "t2.micro"
    Description: Select EC2 Instance Type

  EC2InstanceVolumeType:
    Type: String
    Default: "gp2"
    Description: Select Volume Type

  EC2InstanceVolumeSize:
    Type: String
    Default: "10"
    Description: Insert Volume Size

  EC2InstanceSubnet:
    Type: String
    Default: PublicSubnet
    AllowedValues: [ PublicSubnet ]

  SSHAccessSourceIP:
    Type: String
    Default: "0.0.0.0/0"
    Description: Insert Network Range to allow SSH access

Resources:
# IAM Profile
  EC2IAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${Project}-Role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM"
        - "arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess"

  EC2InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        - Ref: "EC2IAMRole"
      InstanceProfileName: !Sub "${Project}-Profile"

#  EC2Instance
  Manager:
    Type: "AWS::EC2::Instance"
    Properties:
      Tags:
        - Key: Project
          Value: !Ref "Project"
        - Key: Name
          Value: !Sub "${Project}-manager"
      ImageId: !Ref "EC2InstanceAMI"
      InstanceType: !Ref "EC2InstanceInstanceType"
      KeyName: !Ref "KeyPairName"
      IamInstanceProfile: !Ref "EC2InstanceProfile"
      DisableApiTermination: false
      EbsOptimized: false
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            DeleteOnTermination: true
            VolumeType: !Ref "EC2InstanceVolumeType"
            VolumeSize: !Ref "EC2InstanceVolumeSize"
      SecurityGroupIds:
        - !Ref "ManagedSecurityGroup"
      SubnetId: { "Fn::ImportValue": !Sub "${Project}-${EC2InstanceSubnet}" }
      UserData: !Base64 |
        #! /bin/bash
        yum update -y

  Node1:
    Type: "AWS::EC2::Instance"
    Properties:
      Tags:
        - Key: Project
          Value: !Ref "Project"
        - Key: Name
          Value: !Sub "${Project}-node1"
      ImageId: !Ref "EC2InstanceAMI"
      InstanceType: !Ref "EC2InstanceInstanceType"
      KeyName: !Ref "KeyPairName"
      IamInstanceProfile: !Ref "EC2InstanceProfile"
      DisableApiTermination: false
      EbsOptimized: false
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            DeleteOnTermination: true
            VolumeType: !Ref "EC2InstanceVolumeType"
            VolumeSize: !Ref "EC2InstanceVolumeSize"
      SecurityGroupIds:
        - !Ref "ManagedSecurityGroup"
      SubnetId: { "Fn::ImportValue": !Sub "${Project}-${EC2InstanceSubnet}" }
      UserData: !Base64 |
        #! /bin/bash
        yum update -y

  Node2:
    Type: "AWS::EC2::Instance"
    Properties:
      Tags:
        - Key: Project
          Value: !Ref "Project"
        - Key: Name
          Value: !Sub "${Project}-node2"
      ImageId: !Ref "EC2InstanceAMI"
      InstanceType: !Ref "EC2InstanceInstanceType"
      KeyName: !Ref "KeyPairName"
      IamInstanceProfile: !Ref "EC2InstanceProfile"
      DisableApiTermination: false
      EbsOptimized: false
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            DeleteOnTermination: true
            VolumeType: !Ref "EC2InstanceVolumeType"
            VolumeSize: !Ref "EC2InstanceVolumeSize"
      SecurityGroupIds:
        - !Ref "ManagedSecurityGroup"
      SubnetId: { "Fn::ImportValue": !Sub "${Project}-${EC2InstanceSubnet}" }
      UserData: !Base64 |
        #! /bin/bash
        yum update -y

# SecurityGroup for Managed
  ManagedSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      VpcId: { "Fn::ImportValue": !Sub "${Project}-Vpc" }
      GroupName: !Sub "${Project}-SecurityGroup"
      GroupDescription: "-"
      Tags:
        - Key: Project
          Value: !Ref "Project"
        - Key: "Name"
          Value: !Sub "${Project}-SecurityGroup"
# Rule
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref "SSHAccessSourceIP"

#  ElasticIP
  ManagerEIP:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: vpc

  ManagerEIPAssociate:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt ManagerEIP.AllocationId
      InstanceId: !Ref "Manager"

  Node1EIP:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: vpc

  Node1EIPAssociate:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt Node1EIP.AllocationId
      InstanceId: !Ref "Node1"

  Node2EIP:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: vpc

  Node2EIPAssociate:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt Node2EIP.AllocationId
      InstanceId: !Ref "Node2"

Outputs:
#EC2Instance
  ManagerID:
    Value: !Ref "Manager"
    Export:
      Name: !Sub "${Project}-Manager-Id"

  ManagerPrivateIp:
    Value: !GetAtt Manager.PrivateIp
    Export:
      Name: !Sub "${Project}-Manager-PrivateIp"

  ManagerEIP:
    Value: !GetAtt Manager.PublicIp
    Export:
      Name: !Sub "${Project}-Manager-Eip"

  ManagerRoleName:
    Value: !Sub "${Project}-Manager-Role"
    Export:
      Name: !Sub "${Project}-Manager-RoleName"

  Node1ID:
    Value: !Ref "Node1"
    Export:
      Name: !Sub "${Project}-Node1-Id"

  Node1PrivateIp:
    Value: !GetAtt Node1.PrivateIp
    Export:
      Name: !Sub "${Project}-Node1-PrivateIp"

  Node1EIP:
    Value: !GetAtt Node1.PublicIp
    Export:
      Name: !Sub "${Project}-Node1-Eip"

  Node1RoleName:
    Value: !Sub "${Project}-Node1-Role"
    Export:
      Name: !Sub "${Project}-Node1-RoleName"

  Node2ID:
    Value: !Ref "Node2"
    Export:
      Name: !Sub "${Project}-Node2-Id"

  Node2PrivateIp:
    Value: !GetAtt Node2.PrivateIp
    Export:
      Name: !Sub "${Project}-Node2-PrivateIp"

  Node2EIP:
    Value: !GetAtt Node2.PublicIp
    Export:
      Name: !Sub "${Project}-Node2-Eip"

  Node2RoleName:
    Value: !Sub "${Project}-Node2-Role"
    Export:
      Name: !Sub "${Project}-Node2-RoleName"
