AWSTemplateFormatVersion: "2010-09-09"
Description:
  Create VPC and Subnet

Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "Creating VPC and Subnet"
        Parameters:
          - Project
      - Label:
          default: "VPC Network Configuration"
        Parameters:
          - VPCCIDR
          - AZ1Parameter
          - PublicSubnetCIDR

Parameters:
  Project:
    Type: String
    Default: "k8s"
    Description: Project Name

  VPCCIDR:
    Type: String
    Default: "10.0.0.0/16"
    Description: VPC Network

  AZ1Parameter:
    Type: String
    Default: 'us-west-1b'
    Description: Select Availability Zone 1

  PublicSubnetCIDR:
    Type: String
    Default: "10.0.0.0/24"
    Description: Select Subnet in AZ1

Resources:
  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: !Ref "VPCCIDR"
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      InstanceTenancy: default
      Tags:
        - Key: Project
          Value: !Ref "Project"
        - Key: Name
          Value: !Sub "${Project}-VPC"
# Internet Gateway
  InternetGateway:
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
        - Key: Project
          Value: !Ref "Project"
        - Key: Name
          Value: !Sub "${Project}-IGW"

  InternetGatewayAttachment:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      InternetGatewayId: !Ref "InternetGateway"
      VpcId: !Ref "VPC"

# Subnet
  PublicSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Ref "AZ1Parameter"
      CidrBlock: !Ref "PublicSubnetCIDR"
      VpcId: !Ref "VPC"
      Tags:
        - Key: Project
          Value: !Ref "Project"
        - Key: Name
          Value: Public-Subnet

# Route Table
  PublicRouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref "VPC"
      Tags:
        - Key: Project
          Value: !Ref "Project"
        - Key: Name
          Value: Public-Route

  PublicRoute:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref "PublicRouteTable"
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref "InternetGateway"

# RouteTable Associate
  PublicSubnetRouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: !Ref "PublicSubnet"
      RouteTableId: !Ref "PublicRouteTable"

# NetworkAcl
  InternalNetworkAcl:
    Type: "AWS::EC2::NetworkAcl"
    Properties:
      VpcId:
        Ref: "VPC"

  InboundNetworkAclEntry:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref "InternalNetworkAcl"
      RuleNumber: "100"
      Protocol: "-1"
      RuleAction: "allow"
      Egress: "false"
      CidrBlock: !Ref "PublicSubnetCIDR"
      PortRange:
        From: "0"
        To: "65535"

  OutboundNetworkAclEntry:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref "InternalNetworkAcl"
      RuleNumber: "100"
      Protocol: "-1"
      RuleAction: "allow"
      Egress: "true"
      CidrBlock: !Ref "PublicSubnetCIDR"
      PortRange:
        From: "0"
        To: "65535"

Outputs:
  VPC:
    Description: VPC ID
    Value: !Ref "VPC"
    Export:
      Name: !Sub "${Project}-Vpc"

  VPCCIDR:
    Description: VPC CIDR
    Value: !Ref "VPCCIDR"
    Export:
      Name: !Sub "${Project}-VpcCidr"

  PublicSubnet:
    Description: "Public Subnet, AZ:1, Range: 10.0.0.0/24"
    Value: !Ref "PublicSubnet"
    Export:
      Name: !Sub "${Project}-PublicSubnet"

  PublicSubnetCIDR:
    Description: "Public Subnet CIDR, AZ:1, Range: 10.0.0.0/24"
    Value: !Ref "PublicSubnetCIDR"
    Export:
      Name: !Sub "${Project}-PublicSubnetCidr"

  PublicRouteTable:
    Description: "Public Route, AZ:1, Route: Local/Internet"
    Value: !Ref "PublicRouteTable"
    Export:
      Name: !Sub "${Project}-PublicRoute"
